-- V10: CMS block theo spec FE: config (JSON) lưu ở cột data (nay là TEXT), thêm target_segment, mở rộng danh sách type
-- (BANNER, PRODUCT_CAROUSEL, PRODUCT_LIST, INFO_CARDS, IMAGE_GALLERY, PRODUCT_CATEGORY_NAV, PRODUCT_COLLECTION_SHOWCASE,
-- PRODUCT_EXPANDABLE_DESCRIPTION). Block HERO cũ (không có trong spec) được đổi thành INFO_CARDS.

ALTER TABLE cms_blocks DROP CONSTRAINT IF EXISTS ck_cms_blocks_type;
UPDATE cms_blocks SET type = 'INFO_CARDS' WHERE type = 'HERO';
ALTER TABLE cms_blocks ALTER COLUMN type TYPE VARCHAR(40);
ALTER TABLE cms_blocks ALTER COLUMN data TYPE TEXT;
ALTER TABLE cms_blocks ADD COLUMN IF NOT EXISTS target_segment VARCHAR(60);
ALTER TABLE cms_blocks ADD CONSTRAINT ck_cms_blocks_type CHECK (type IN ('BANNER', 'PRODUCT_CAROUSEL', 'PRODUCT_LIST', 'INFO_CARDS', 'IMAGE_GALLERY', 'PRODUCT_CATEGORY_NAV', 'PRODUCT_COLLECTION_SHOWCASE', 'PRODUCT_EXPANDABLE_DESCRIPTION'));
