-- V2: bổ sung schema cho các domain ADMIN chưa có bảng ở V1 (Catalog.attributes mục J, CMS mục O,
-- Badge mục P) - THÊM MỚI, không sửa V1 (đúng rule "không sửa migration đã có"). Theo
-- document/09-tong-hop-api-fe.md. Inventory (mục M) KHÔNG có bảng riêng ở đây - xem
-- claude/RULE-CODE.md mục Inventory admin: dùng thẳng on_hand/reserved có sẵn ở product_skus (V1),
-- hệ thống tạm coi như 1 kho mặc định duy nhất (warehouseId cố định "MAIN"), CHƯA hỗ trợ đa kho thật.

-- ===================== THUỘC TÍNH SẢN PHẨM (Admin Catalog - mục J) =====================
CREATE TABLE product_attributes (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(120) NOT NULL,
    code          VARCHAR(60) NOT NULL,
    type          VARCHAR(20) NOT NULL,
    options       VARCHAR(2000),
    created_id    BIGINT,
    created_date  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_id    BIGINT,
    updated_date  TIMESTAMPTZ,
    CONSTRAINT uq_product_attributes_code UNIQUE (code),
    CONSTRAINT ck_product_attributes_type CHECK (type IN ('TEXT', 'SELECT', 'MULTISELECT'))
);

-- ===================== CMS (mục O) =====================
CREATE TABLE cms_pages (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug          VARCHAR(140) NOT NULL,
    title         VARCHAR(200) NOT NULL,
    status        VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    created_id    BIGINT,
    created_date  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_id    BIGINT,
    updated_date  TIMESTAMPTZ,
    deleted_id    BIGINT,
    deleted_date  TIMESTAMPTZ,
    CONSTRAINT uq_cms_pages_slug UNIQUE (slug),
    CONSTRAINT ck_cms_pages_status CHECK (status IN ('DRAFT', 'PUBLISHED'))
);

CREATE TABLE cms_blocks (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    page_id       BIGINT NOT NULL REFERENCES cms_pages (id) ON DELETE CASCADE,
    type          VARCHAR(30) NOT NULL,
    sort_order    INTEGER NOT NULL DEFAULT 0,
    data          VARCHAR(4000),
    created_id    BIGINT,
    created_date  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_id    BIGINT,
    updated_date  TIMESTAMPTZ,
    CONSTRAINT ck_cms_blocks_type CHECK (type IN ('BANNER', 'PRODUCT_CAROUSEL', 'HERO'))
);
CREATE INDEX ix_cms_blocks_page ON cms_blocks (page_id);

-- ===================== BADGE (mục P) =====================
CREATE TABLE badge_templates (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(120) NOT NULL,
    label_text    VARCHAR(60) NOT NULL,
    color         VARCHAR(20),
    created_id    BIGINT,
    created_date  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_id    BIGINT,
    updated_date  TIMESTAMPTZ,
    deleted_id    BIGINT,
    deleted_date  TIMESTAMPTZ
);

CREATE TABLE badge_flow (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    badge_id       BIGINT NOT NULL REFERENCES badge_templates (id) ON DELETE CASCADE,
    rule_type      VARCHAR(20) NOT NULL,
    rule_ref_id    BIGINT,
    channel        VARCHAR(20) NOT NULL DEFAULT 'ALL',
    priority       INTEGER NOT NULL DEFAULT 0,
    active         BOOLEAN NOT NULL DEFAULT TRUE,
    created_id     BIGINT,
    created_date   TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_id     BIGINT,
    updated_date   TIMESTAMPTZ,
    CONSTRAINT ck_badge_flow_rule_type CHECK (rule_type IN ('MANUAL', 'ALL', 'CATEGORY', 'COLLECTION', 'PROMOTION', 'OUT_OF_STOCK')),
    CONSTRAINT ck_badge_flow_channel CHECK (channel IN ('ALL', 'WEB', 'MOBILE_WEB', 'APP'))
);
CREATE INDEX ix_badge_flow_badge ON badge_flow (badge_id);
